name: PHP Lint

on: [push, pull_request]

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run PHP Linter
        run: |
          find . -type f -name "*.php" -exec php -l {} \;
